name: covidboosters
channels:
 - conda-forge
 - bioconda
 - nodefaults
dependencies:
 - numpy
 - scipy
 - matplotlib
 - seaborn
 - pandas
 - joblib
 - tqdm
 - cftime
 - svgutils
 - snakemake
 #Linting
 - ruff
 #Notebooks
 - ipykernel

